### ISSUE TITLE
fairseq-preprocess: error: argument --task

### ISSUE THREAD

**Issue by Joelqi** [ZhaofengWu/rfa-doc-mt#2]
Hello, we are using version 0.10.0 of fairseq，but we use ./prepare_ted.sh, the error said 
"fairseq-preprocess: error: argument --task: invalid choice: 'doc_translation' ."

I want to ask how to solve,Thank you.

**Comment by ZhaofengWu** [comment]
Ah, yes, good question. So fairseq needs to know what our `doc_translation` task is. The way that we did this is by setting `export PYTHONPATH="$(pwd):${PYTHONPATH}"` like in https://github.com/ZhaofengWu/rfa-doc-mt/blob/master/train_baseline.sh.

**Comment by Joelqi** [comment]
> Ah, yes, good question. So fairseq needs to know what our `doc_translation` task is. The way that we did this is by setting `export PYTHONPATH="$(pwd):${PYTHONPATH}"` like in https://github.com/ZhaofengWu/rfa-doc-mt/blob/master/train_baseline.sh.

Thanks for your answer!
